BUG: Regression: CmdEntity.getName() references global function id()
Found during exploratory testing of the mcpi API.
,----[ mcpi REPL ]----
| In [14]: mc.getNearbyEntities(mc.player.getPos())[0].getName()
| RequestError: b'entity.getName(<built-in function id>,)' failed
`----

The ID is now stored in the super class's entityID attribute.

Note: This will still fail as entity.getName isn't yet implemented in JuicyRaspberryPie.
> RequestError: b'entity.getName(712a298c-2edb-4ab9-a950-01b577826e10,)' failed