FIX: Regression: CmdEntity.remove() still requires id argument
,----[ mcpi REPL ]----
| In [13]: mc.getNearbyEntities(mc.player.getPos())[0].remove()
| TypeError                                 Traceback (most recent call last)
| Cell In[13], line 1
| ----> 1 mc.getNearbyEntities(mc.player.getPos())[0].remove()
| TypeError: Entity.remove() missing 1 required positional argument: 'id'
`----

The ID is now stored in the super class's entityID attribute. Here, it was also forgotten to remove the id argument.